# Exported from Render on 2025-07-09T01:38:15Z
services:
- type: web
  name: expert-layer
  runtime: node
  repo: https://github.com/Davheed2/expert-layer
  plan: starter
  envVars:
  - key: STRIPE_WEBHOOK_SECRET
    sync: false
  - key: STRIPE_SECRET_KEY
    sync: false
  - key: REFRESH_TOKEN_EXPIRES_IN
    sync: false
  - key: REFRESH_TOKEN
    sync: false
  - key: R2_TOKEN_VALUE
    sync: false
  - key: R2_SECRET_ACCESS_KEY
    sync: false
  - key: R2_REGION
    sync: false
  - key: R2_PUBLIC_URL
    sync: false
  - key: R2_CDN_URL
    sync: false
  - key: R2_BUCKET_NAME
    sync: false
  - key: R2_ACCOUNT_ID
    sync: false
  - key: R2_ACCESS_KEY_ID
    sync: false
  - key: QUEUE_REDIS_URL
    sync: false
  - key: QUEUE_REDIS_PORT
    sync: false
  - key: QUEUE_REDIS_PASSWORD
    sync: false
  - key: NODE_ENV
    sync: false
  - key: GMAIL_USER
    sync: false
  - key: GMAIL_PASSWORD
    sync: false
  - key: FRONTEND_URL
    sync: false
  - key: DB_USER
    sync: false
  - key: DB_PORT
    sync: false
  - key: DB_PASSWORD
    sync: false
  - key: DB_HOST
    sync: false
  - key: DB_DATABASE
    sync: false
  - key: AUTH_SECRET
    sync: false
  - key: APP_PORT
    sync: false
  - key: APP_NAME
    sync: false
  - key: ACCESS_TOKEN_EXPIRES_IN
    sync: false
  - key: ACCESS_TOKEN
    sync: false
  region: ohio
  buildCommand: npm install && npm run build
  startCommand: npm run start-prod
  autoDeployTrigger: commit
version: "1"
